baseURL = "http://example.org/"
languageCode = "en-us"
title = "VegBook"
theme = "hugo-theme-techdoc"
[outputs]
  home = ["HTML", 'JSON', "AMP", "RSS"]
  section = ['HTML', 'JSON']
  page = ["HTML", "JSON"]
