baseURL = "https://talkveganto.me/"
DefaultContentLanguage = "en"
theme = "hugo-theme-techdoc"
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    title = "TalkVeganToMe"
    contentDir = "content/english"
    languageName = "English"
    weight = 10
  [languages.fr]
    title = "TalkVeganToMe"
    contentDir = "content/french"
    languageName = "French"
    weight = 20

[outputs]
  home = ["HTML", 'JSON']
  section = ['HTML', 'JSON']
  page = ["HTML", "JSON"]
